### ISSUE TITLE
electron doesnt terminate completely

### ISSUE THREAD

**Issue by blurymind** [p-sam/electron-prompt#12]
When using this, when closing the electron window of the app to terminate the app, it will not terminate completely

**Comment by p-sam** [comment]
Could you tell me with more details what you're expecting and what actually happens?

**Comment by blurymind** [comment]
The expected behavior is when the main app has been closed/terminated, the prompt should also terminate.

It doesnt, perhaps somehow related to not having a parent window?

To replicate:
1. open prompt
2. without closing it, close the main app

It doesnt close, and when you try to close it - you get javascript error:
`Attempting to call a function in renderer window that has been closed or released...`

**Comment by p-sam** [comment]
Thanks for the details, indeed both of your issues might be related to the fact it doesn't have a parent window, or rather, that it doesn't take account of the parentWindow argument when used in a renderer process context. I never used it outside of the main process, so i'm not sure what exactly is going on. Could you make sure that the prompt fonction pass a coherent parentWindow value to the browserWindow constructor ?

**Comment by blurymind** [comment]
Ah I see.

`console.log(remote.getCurrentWindow()) `
does give me a valid window object

but when using
`parentWindow :remote.getCurrentWindow()`

I get
```
F:\stuff\elAPP\node_modules\electron-prompt\lib\index.js:38 Uncaught TypeError: Converting circular structure to JSON
```
and the prompt doesnt even initialize properly

**Comment by blurymind** [comment]
I also tried passing the main window from main.js as a variable to the renderer on initialization.
I get the same problems, but at least the prompt initializes

**Comment by blurymind** [comment]
Ok, I passed it like this and I didnt get any errors:
```
		prompt({
		title: 'Create New Chapter',
		label: 'Please enter the new Chapters Name:',
		value: 'new',
		//// parentWindow : parentMainWindow, <<- wrong way?
		inputAttrs:{type: ''}},
                remote.getCurrentWindow()) //<<- right way?
                .then((newname) => {
			console.log('result', newname); // null if window was closed, or user clicked Cancel
			if (newname.length==0){alert("You didnt enter a name");return};
			createNew(newname);
			}).catch(console.error);
```
But that doesnt resolve the issue here. The prompt doesnt get terminated when I close the app

**Comment by p-sam** [comment]
I have not been able to replicate the error, could you provide me a working example of code that can trigger the error when the "window has been released" ?

**Comment by blurymind** [comment]
@sperrichon Have you been able to initiate the prompt from a renderer process, attaching it to the parent window via remote.getCurrentWindow() ?
I thought that would solve it, but it doesn't :( 

In that case, can you provide the code?

I will look into making a minimal project example

**Comment by p-sam** [comment]
I have not been testing anything, tho I intend to try something too later today

**Comment by p-sam** [comment]
Fixed by PR #16

**Comment by blurymind** [comment]
Thank you for the fix 👍 :) 

I will test this again when I have some time

**Comment by p-sam** [comment]
no problem, feel free to reopen the issue in case the problem would not totally resolved.
