### ISSUE TITLE
Needs more documentation

### ISSUE THREAD

**Issue by kylecorry31** [p-sam/electron-prompt#13]
The options for the prompt are not specified in written documentation for example.

**Comment by p-sam** [comment]
Hi,

Could you provide me in more details what are missing, or lack details in the example stated in the README? I have made no real documentation other than that

**Comment by kylecorry31** [comment]
One thing that I needed to do was make a text prompt, and I had to read through the implementation code to find that I needed to have the input type as input. The example only shows the select type, so I would definitely find it useful to see how to use the other types (input, select, whatever else there is) and how to go about using them, either in docs format or examples.

**Comment by p-sam** [comment]
I see, I thought the example to be sufficient as it says about type possible values and what params are used when type is set 'input' and what params when it's on 'select'. Do you have a proposal for an example, that would be better than the one I currently have ? PR appreciated :)

**Comment by kylecorry31** [comment]
Wow, I seemed to have missed those comments haha, I might PR an example using the input type as that may be more visible than the comments on the example.

The only question on documentation I have now would be the inputAttrs and what they can be

**Comment by p-sam** [comment]
No problem, the inputAttrs are every attribute you want to put in the input element. (only used if type is input)
ex: {type: 'text', required: true} -> `<input type="text" required>`
{type: 'url'} -> `<input type="url">`

**Comment by kylecorry31** [comment]
That makes since, I'll try to do a PR today with some more documentation, thanks!

**Comment by Fraasi** [comment]
Now that you have a nice little documentation, you really should move it from the developer branch to master. Makes it easier to find 😃
