### ISSUE TITLE
On multiple screen, prompt stays on main screen

### ISSUE THREAD

**Issue by CptMaumau** [p-sam/electron-prompt#18]
I am using version 1.1.0 and testing on a macbook with 2 extra monitors.
When my application window is on one of the extra monitors and I trigger the prompt, it always appears on the main screen.
I think it should appear where the triggering window is currently in.
I have run into similar issues for my project and know that you can use the API electron.screen for this.

**Comment by p-sam** [comment]
have you tried passing your window as the parentWindow option ? prompt stays on top of the parent window even on a a secondary monitor or when the window is moved

**Comment by CptMaumau** [comment]
Thank you, I didn't understand right away this option but now it's working. Thank you for your time!
