### ISSUE TITLE
Clipboard pasting in the prompts?

### ISSUE THREAD

**Issue by dwetscher** [p-sam/electron-prompt#2]
I am using your example for prompting a user for a URL. However most users will copy those to the clipboard and then paste it to the text field. Is there a way to enable that?

**Comment by p-sam** [comment]
It doesn't display a contextual menu on right click, though keyboard shortcuts for selection, copy, and pasting should work just fine.

**Comment by dwetscher** [comment]
Not sure if it is a specific issue on macos, but keyboard shortcuts do not work for me. I will try to debug it and come bavk to you with more details.

**Comment by dwetscher** [comment]
After re-creating my application menu for OSX copy/paste works as expected - no issue indeed.
