### ISSUE TITLE
Close the window when the Esc key has been clicked

### ISSUE THREAD

**Issue by thewizardplusplus** [p-sam/electron-prompt#22]
It's default behavior of dialog windows in many platforms and frameworks. Electron `dialog` module support it too.

If you don't want to do this by default, you can add an option for this.

And I'm ready to make a pull request of course.

**Comment by p-sam** [comment]
Yes, it should have the default behavior of most OS prompt windows, so I like the idea of doing it by default

**Comment by p-sam** [comment]
resolved by #25
