### ISSUE TITLE
Select a whole default text in the input element when the window has been opened

### ISSUE THREAD

**Issue by thewizardplusplus** [p-sam/electron-prompt#23]
It's default behavior of the `prompt` function in JavaScript. Thanks to this, you can immediately start typing a text as soon as the window is open. Default text will be erased automatically.

If you don't want to do this by default, you can add an option for this.

And I'm ready to make a pull request of course.

**Comment by p-sam** [comment]
Yup, like #22, it's a good idea to have that as default

**Comment by p-sam** [comment]
resolved by #24
