### ISSUE TITLE
mac ios 10 can't paste

### ISSUE THREAD

**Issue by w4567892015** [p-sam/electron-prompt#26]
hi! I have trouble in mac os version 10.13.6. I wanted to paste some string on the input, but failed. Need you help. Thanks

**Comment by p-sam** [comment]
Hello, I'm on MacOS 10.13.6 too, I can copy, cut, and past in the field just fine. Did you try using keyboard shortcuts?

**Comment by w4567892015** [comment]
Yes, I have used keyboard shortcuts to paste, but it field.

**Comment by p-sam** [comment]
Then I'm not sure what you problem is, I'm not able to reproduce the bug myself

**Comment by w4567892015** [comment]
Okay! I try to search for some answer. So I have solved this problem. Use [this](https://www.codedmaster.com/2017/01/24/getting-electron-copy-paste-shortcuts-for-mac-builds/)  . Thank for your help.  :)

**Comment by p-sam** [comment]
I see, nice find, the applications where I used electron-prompt all have a working menu with edit actions. I'm closing the issue then.
