### ISSUE TITLE
Could not find a declaration file for module 'electron-prompt'

### ISSUE THREAD

**Issue by medbenchohra** [p-sam/electron-prompt#33]
Hello, the prompt can't get the input, it returns an empty string.

VS Code says: "Could not find a declaration file for module 'electron-prompt' "

**Comment by p-sam** [comment]
Hi,

As I gather from the error code you sent to me, you seem to be using Typescript, and/or VS Code may be using it for auto-completion. This was not designed with Typescript in mind, and I didn't try or intend to use it in such way.

**Comment by medbenchohra** [comment]
Thank you.
