### ISSUE TITLE
Dialog only shows white background

### ISSUE THREAD

**Issue by erikjalevik** [p-sam/electron-prompt#34]
I just tried this lib out on OSX, following the instructions in the readme exactly, and the dialog appears but it's just a titlebar with a completely white pane underneath. Tried both from renderer and main process.

Any idea what I'm doing wrong?

**Comment by p-sam** [comment]
I'm not sure, I just tried latest 1.3.0 on OSX 10.14.3 with node v11.7.0 without issue, try to spawn the devtools of the created browserWindow to diagnose what's going on

**Comment by erikjalevik** [comment]
Sorry, I will just close this as I made a home-rolled HTML prompt in the meantime. Probably some weird issue on my end. :)

**Comment by garviand** [comment]
Having this issue as well

**Comment by beautyfree** [comment]
Same

**Comment by cawa-93** [comment]
Same. I have error in dialog window

```
Not allowed to load local resource: file:///Users/Alex/Develop/play-shiki-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/page/prompt.html#1576308387511-0.7777359584319303
```

**Comment by rob10e** [comment]
I had the same problem. I solved mine by using 
`window.require('electron-prompt')` instead of
`require('electron-prompt')`

**Comment by camhart** [comment]
I'm facing this as well on Mac OS Catalina.  Completely white.  I'm trying to use it from the main thread (not a renderer thread).

**Comment by trandaison** [comment]
I'm using this this on main thread to performance a login before creating a browser window. But everything is empty
```js
app.on('ready', async () => {
  const password = await prompt({
    title: 'Login',
    label: 'Password',
    value: '',
    inputAttrs: {
      type: 'password'
    },
    type: 'input',
  });
});
```
