### ISSUE TITLE
Feature request : Option to hide the Menu Bar

### ISSUE THREAD

**Issue by Lurivar** [p-sam/electron-prompt#37]
Adding an option to hide the window menu bar like you can do when you create a new window yourself ( with setMenuBarVisibility(false) ) would be nice.

**Comment by yafp** [comment]
I was just going to create an issue myself for exact the same reason :)

**Comment by sanappa** [comment]
Created a gist of the required changes: https://gist.github.com/sanappa/ce493991316cf07d6fa1676c0e031daf

**Comment by p-sam** [comment]
Hi, you can go and make the PR, LGTM.
