### ISSUE TITLE
icon - formats, sizes - known limitations?

### ISSUE THREAD

**Issue by yafp** [p-sam/electron-prompt#38]
Which image formats are supported?

I seem unable to use the icon feature as i always see the default icon. So far i am unsure what the problem is ....either wrong format or size or just not finding the referenced image.

Is there a way to debug the icon option?

**Comment by p-sam** [comment]
This justs spawns a BrowserWindow under the hood, check the electron docs on the subject

**Comment by yafp** [comment]
sorry i forgot to use __dirname.

Thanks.
