### ISSUE TITLE
Can not work with app without a main window

### ISSUE THREAD

**Issue by ghost** [p-sam/electron-prompt#42]
When the app has no main windows, e.g. apps with tray menu only, clicking either `Cancel` or `OK` of the prompt dialog will causes the app exits.

I am using macOS.

**Comment by p-sam** [comment]
My guess is you're listening for the event `window-all-closed` to quit the app, and it's just what is happening. Your only and last window closes when you click either of those buttons.

**Comment by noeruh** [comment]
Emmm, it's indeed caused by the window-all-closed event, but I haven't listening for that event myself, it's Electron's default behavior.

I solved this issue by manually listening on the window-all-closed event to override Electron's default behavior and do nothing in the callback.
