### ISSUE TITLE
Regression on the v1.5.0 when hitting the enter key

### ISSUE THREAD

**Issue by edouardmercier** [p-sam/electron-prompt#54]
I noticed that a regression was introduced, from v1.4.0 to v1.5.0: when the input is focused and the end-user presses the "Enter" key, the prompt dialog is dismissed as if the user had pressed the "Cancel" button, instead of the "OK" button.

**Comment by Fraasi** [comment]
This has to do with the new version using `<form>`, where enter submits the form.
Thus the `keyup` event never fires and doesn't call `promptSubmit`.
https://javascript.info/forms-submit

You can fix this simply by using `keydown` event, which apparently fires before submit and prevents it. `keypress`  event on the other hand somehow fixed the `enter` problem but broke using `escape`.
It would propably be good to call  `e.preventDefault()` also, but I find it's not necessary here.
Weird problem, could someone else also test this just to make sure?
```
		dataEl.addEventListener('keydown', e => {
			if (e.key === 'Enter') {
				// e.preventDefault()
				promptSubmit();
			}
			if (e.key === 'Escape') {
				promptCancel();
			}
```

**Comment by p-sam** [comment]
Yup, this was introduced when I added form validation

**Comment by p-sam** [comment]
Can someone confirm me that behavior is back to normal on develop? Will do a minor release right after that

**Comment by edouardmercier** [comment]
@p-sam, a quick test on macOS shows that the modified code does not solve the issue: when hitting the "<Return>" key, the dialog box is still being considered as cancelled.

**Comment by p-sam** [comment]
What key? I tested the latest develop commit on OSX too

If you're trying from the npm package, please switch to the git repo on branch develop just for this test. I'm holding off from publishing a release until the fix is confirmed working (at least for you, others confirmation appreciated too)

**Comment by edouardmercier** [comment]
Sorry @p-sam, when using the dependency `git://github.com/p-sam/electron-prompt#develop` for the `electron-prompt` package, this does not work for me on macOS and `electron` v7.1.9: indeed, once the dialog box with the text field is open and that I hit the "<Enter>" key, the dialog is dismissed as if the "Cancel" button were pressed (instead of the "OK" button).

**Comment by p-sam** [comment]
Not sure why but your comments seem to be missing parts, specifically parts between quotes

**Comment by p-sam** [comment]
@edouardmercier The fix in ca0c3ad was tested on electron 7.1.10 and 7.1.9, on OSX too, and hitting the Enter key while in the text input submits the form, and returns me the result I typed, while hitting Esc returns null, as expected.

 If you have any different result, I can't yet reproduce them because as I said, parts of your messages are missing. I will probably do a release later today, unless the fix is not enough in a particular OS/Electron ver combo.

**Comment by edouardmercier** [comment]
@p-sam, I have fixed my previous comment (which was buggy because I used incorrect Markdown). Thank you for having tested your fix on a similar environment as mine: if it is successful by you, this must mean that I must have made a mistake while using the `develop` branch version.

**Comment by p-sam** [comment]
You can try doing a quick `npm update`, what does the package-lock.json says about the package?
