### ISSUE TITLE
Feature Request: allow change of type of input

### ISSUE THREAD

**Issue by alandoyle95** [p-sam/electron-prompt#6]
is it possible to get the input from a text into a select option?

**Comment by p-sam** [comment]
It is not yet possible to prompt for a list of fixed values with a select.
I had a similar use case which I resolved using Electron Menus and checked
items, thus I did not feel the need to include that.
Multiple input types are definitely possible, and a PR would be appreciated
:)

**Comment by alandoyle95** [comment]
already started to work on one haha :)

**Comment by alandoyle95** [comment]
well. I have it all working, but I wanted to check to see if I could get Multiple selects to work as well. but it seems that only the first value is passed back.. so I have to figure out that one before multiple selects would be supported.

**Comment by p-sam** [comment]
Select type support has been pushed to develop.

While technically working, I chose to drop support for multiple select, because of style issues from the select having its height overflowing, and mainly because checkboxes appear to be commonly regarded as a better solution to selecting multiple items.

**Comment by alandoyle95** [comment]
Sounds good to me, does this push mean

npm install would grab this?

**Comment by alandoyle95** [comment]
the `select.html` is missing, and the code to switch to that if `options.type == 'select'` in the development branch. you planning on combining it into one HTML file ?

tried to install dev branch with npm so i could continue with my project and its not working haha, so just wondering :P

**Comment by p-sam** [comment]
Yes I combined both templates, and it's not yet released on npm because I
need to do some styling on the select, and update the documentation.

In the meantime, you can do `npm install sperrichon/electron-prompt#develop` to test if it works for you.

**Comment by p-sam** [comment]
Added in 0.4.0.
