### ISSUE TITLE
Include a LICENSE file at the root of the repo

### ISSUE THREAD

**Issue by johannesjo** [p-sam/electron-prompt#61]
It would be super cool if you could add an open-source license to your project. Without it, everybody is at legal risk when using your lib.

**Comment by p-sam** [comment]
https://github.com/p-sam/electron-prompt/blob/develop/package.json#L19

**Comment by johannesjo** [comment]
That's not enough afaik. You need to add an actual LICENCE to the repo.

**Comment by p-sam** [comment]
I'm getting you want a text version at the root of the repo? If that's alright then i'm reopening and editing the title

**Comment by johannesjo** [comment]
Yes. I am not a lawyer, but I would assume that a field in a config file is not enough. Also this way GitHub cannot pick up on it. 

This would be an example:
https://github.com/johannesjo/super-productivity/blob/master/LICENSE
