### ISSUE TITLE
Validate form on Enter/return key pressed

### ISSUE THREAD

**Issue by fperaltaa** [p-sam/electron-prompt#62]
If you add the **pattern** attribute to the input, it is nos being validated when you submit the form pressing "Enter" key.

**Comment by p-sam** [comment]
Seems like a duplicate of #52, can you try on the develop branch and confirm?

**Comment by fperaltaa** [comment]
@p-sam I'm using version 1.5.1 where the input is already inside a form. The pattern is being validated on submit with the "ok" button but not when I hit "Enter".
It is related with #52, we can close this and reopen that one if you wish.

**Comment by p-sam** [comment]
I see, thanks for the clarification

**Comment by p-sam** [comment]
Please confirm the issue is resolved on your end too in the develop branch, then I'll wrap up a new release

**Comment by fperaltaa** [comment]
Thanks @p-sam ! I tried with develop branch and it is working as expected.
