### ISSUE TITLE
Preview electron-prompt

### ISSUE THREAD

**Issue by Zeyu-Li** [p-sam/electron-prompt#68]
Could someone please add a snapshot in the readme such that someone can easily preview what electron-prompt will look like? Thanks

**Comment by p-sam** [comment]
Here's the snapshot that will be added to the README

<img width="482" alt="prompt-preview" src="https://user-images.githubusercontent.com/17620180/111752934-915a0580-8896-11eb-8686-0d2ea80db340.png">

**Comment by p-sam** [comment]
<img width="482" alt="prompt-preview" src="https://user-images.githubusercontent.com/17620180/111753337-09c0c680-8897-11eb-8ce8-43de29c143bd.png">

**Comment by Zeyu-Li** [comment]
thank you 😘
