### ISSUE TITLE
Add typescript support? (`d.ts` file)

### ISSUE THREAD

**Issue by kimlimjustin** [p-sam/electron-prompt#75]
Most packages nowadays include `d.ts` files to support typescript type, so could you please add it here too? thanks

**Comment by Fraasi** [comment]
Looks like someone already made the typings to the definitely typed repo.  Npm page is https://www.npmjs.com/package/@types/electron-prompt

**Comment by p-sam** [comment]
I don't use typescript, and I'm fine with external maintenance of it so I'm closing the issue.
